add_lunch_combo axi0m_mako-userdebug
add_lunch_combo axi0m_maguro-userdebug
add_lunch_combo axi0m_toro-userdebug
add_lunch_combo axi0m_toroplus-userdebug
add_lunch_combo axi0m_xt926-userdebug
add_lunch_combo axi0m_i605-userdebug
